### ISSUE TITLE
Problem: We don't know what the community wants from festival

### ISSUE THREAD

**Issue by julianpistorius** [resbazaz/festival2023#1]
We are guessing at:

1. Date
2. Format
3. Topics of interest

To organize a successful festival we need to cater to our community. To do that we should find out their preferences.

A poll is one way to do that.

**Comment by julianpistorius** [comment]
Stay tuned. We may choose a date that suits most of the community members who are (and will be) investing their time and energy in organizing the festival. Will discuss at next steering committee meeting (Thursday 26 January).

**Comment by val-pf** [comment]
with the survey responses in progress/collected & dates decided, I will mark this issue as complete
