### ISSUE TITLE
Define and formalize event organizer roles

### ISSUE THREAD

**Issue by julianpistorius** [resbazaz/festival2023#10]

**Comment by julianpistorius** [comment]
Suggestions:

- Recruiting and managing panelists, presenters, and workshop instructors (at least one for each campus?)
- Managing volunteers (e.g. online/in-person helpers at workshops)
- Marketing and publicity (social media, etc.)
- Audio-visual and technology for virtual/hybrid events
- Venue reservations at different campuses
- Documentation for future events
- Data gathering and data management (pre-conference surveys, attendees, post-conference surveys)
- Cross-campus coordinators (confirm the point of contact for each campus)
- Organizers of in-person social events

Anything I'm missing? Or any unnecessary/duplicate roles?

**Comment by julianpistorius** [comment]
I think this is done! :clap: Can you please confirm @val-pf?

- :pencil2: **_Administration_** (tasks: create documentation, Data Management, Cross-Campus facilitation, etc).
  - @hidyverse 
  - @julianpistorius 
  - @val-pf 
- :mega: **_Marketing_** (tasks: social media, flyer design, website content & management, venue contacts, etc)
  - @alex-r-bigelow
  - @jcoliver
  - Tina Johnson
- :construction: **_Operations_** (tasks: instructor/speaker & helper organization, social events, etc)
  - @bjoyce3 
  - @Gchism94 
  - @jessicaguo 
  - @lossanna 
  - @LauraFalk

**Comment by val-pf** [comment]
Yes, I think so. Anyone who isn't in a sub committee can still join, but this will hopefully speed things up.
