### ISSUE TITLE
Post survey in other places

### ISSUE THREAD

**Issue by julianpistorius** [resbazaz/festival2023#12]
- [x] ResBaz Slack - @Gchism94 
- [ ] CyVerse Slack - ?
- [x] UA Data Science Slack - @jcoliver 
- [x] R users mailing list - @jcoliver
- [ ] Graduate student listservs (also known as email list service)
    - [x] NAU - @egreich 
    - [ ] ASU - @rbelshe 
    - [x] UArizona - @val-pf ?
- [ ] Meetup - @julianpistorius 
- [ ] Twitter - @julianpistorius 

Where else would be good?

**Comment by rbelshe** [comment]
What does "Grad listservs" mean?

**Comment by val-pf** [comment]
Any listserver that reaches grad students. For UArizona, that's Graduate and Professional Council, the Program Directors, etc.

**Comment by julianpistorius** [comment]
@rbelshe I clarified the wording. Apologies for the jargon. :blush: 

This looks useful:

https://sese.asu.edu/student-clubs-organizations

**Comment by val-pf** [comment]
Added to meeting agenda for tomorrow. Please add any additional updates on this to hackMD or mention during the RezBaz steering committee meeting. 
https://hackmd.io/Az5QpEKtQAazXcdqztYhPQ?both
