### ISSUE TITLE
Create NAU ResBaz website presence

### ISSUE THREAD

**Issue by val-pf** [resbazaz/festival2023#16]
With help from @alex-r-bigelow @hidyverse @julianpistorius and me :)

**Comment by val-pf** [comment]
Change website to be as follows:
schedule
[ASU logo]: Location & Time (with map), highlight in-person events, Registration link, contact info of a ASU person
[NAU logo]: Location & Time (with map), highlight  in-person events, Registration link, contact info of a NAU person
[UA logo]: Location & Time (with map), highlight in in-person events (e.g. speaker, hacky hour), Registration link, contact info of a UA person

NAU website with basic info as above & contacts for NAU people

**Comment by alex-r-bigelow** [comment]
Noting per today's meeting: won't be bothering with logos

**Comment by julianpistorius** [comment]
As for dedicated NAU & ASU ResBaz websites:To discuss at or after festival.

**Comment by alex-r-bigelow** [comment]
Before closing this out, do we have any ASU / NAU orgs that we should list as sponsors?

(Also we should probably reconsider the word "Sponsor" ... Any thoughts on switching to "Supporter?")

**Comment by egreich** [comment]
Maybe for NAU add Informatics Graduate Student Association (https://igsa-siccs.github.io/) and T3 Ecological and Environmental Informatics (https://ecoinfo.nau.edu/)

**Comment by julianpistorius** [comment]
> Maybe for NAU add Informatics Graduate Student Association (https://igsa-siccs.github.io/) and T3 Ecological and Environmental Informatics (https://ecoinfo.nau.edu/)

Thank you @egreich! I created a follow-up issue: #28
