### ISSUE TITLE
Ask Emma to join Operations Team, ideally Admin and Marketing Teams as well

### ISSUE THREAD

**Issue by julianpistorius** [resbazaz/festival2023#18]
- @resbazaz/festival-operations : Instructor/speaker & helper organization, social events
- @resbazaz/festival-administration : Create documentation, Data Management, Cross-Campus facilitation
- @resbazaz/festival-marketing : Social media, flyer design, website content & management, venue contacts

Context: https://github.com/resbazaz/festival2023/wiki/Meetings---Admin-Team#2023-03-15

**Comment by Gchism94** [comment]
Emma is currently working with us on Operations

**Comment by hidyverse** [comment]
ResBaz AZ Flagstaff team (@egreich, Alicia, and Kat) followed-up with via emailed 3/16/23 and invited to join sub-committees.
