### ISSUE TITLE
Talk to ICDI about sponsoring coffee and snacks for in-person attendees

### ISSUE THREAD

**Issue by julianpistorius** [resbazaz/festival2023#21]

**Comment by Gchism94** [comment]
Email sent. Awaiting reply.

**Comment by julianpistorius** [comment]
From @Gchism94 

> CDI got back to me about sponsorship and we need to provide the following:
> 
> Name of event
> Date
> Vendor we want to use
> What we need
> Count of people we need to feed/support
> 
> Support sub-committee, is this something you can tackle?

**Comment by julianpistorius** [comment]
Done! @Gchism94 says they've paid the bill.
