### ISSUE TITLE
Problem: We are not spreading ResBaz goodness to NAU & ASU

### ISSUE THREAD

**Issue by julianpistorius** [resbazaz/festival2023#3]
Would be great to involve NAU & ASU folks.

**Comment by Aariq** [comment]
had attendees from NAU on Nov 3 meeting

**Comment by Aariq** [comment]
Eric will contact Reed Cartwright at ASU who contacted Eric about proposal to create data science training program at ASU

**Comment by jcoliver** [comment]
Jeff will contact Kerri Rittschof at ASU (data science in library)

**Comment by julianpistorius** [comment]
It sounds like we have momentum and buy-in at both NAU and ASU. :tada:

**Comment by julianpistorius** [comment]
I think this is addressed . We should create specific issues for NAU & ASU festival.
