### ISSUE TITLE
Problem: Reprohack we don't know what's involved

### ISSUE THREAD

**Issue by julianpistorius** [resbazaz/festival2023#4]
Reprohack sounds great, but we don't know what's involved. There are a number of ways to do it.

- [ ] Look at [Reprohack site](https://www.reprohack.org/)
- [ ] Fill in organizer template
- [ ] Report back to steering committee with ideas and a rough plan

**Comment by Aariq** [comment]
Organizer template: https://docs.google.com/spreadsheets/d/1E9sGbZApmt73wdgn5exG7YtNedPMF_IzfLtrFuY9oL8/edit#gid=0

**Comment by val-pf** [comment]
@Aariq won't be able to host this, and the temporal frame of ResBaz festival 2023 might be too narrow. Consider a repro hack as a stand-alone event maybe in late Summer/ early Fall.
