### ISSUE TITLE
Problem: We don't have a clear and concise way to convey value of ResBaz

### ISSUE THREAD

**Issue by julianpistorius** [resbazaz/festival2023#5]
Would be great if we could send materials to potential collaborators, presenters, and attendees.

**Comment by Aariq** [comment]
Website update: https://github.com/resbazaz/studyGroup/pull/35/files
Text to send to collaborators: https://docs.google.com/document/d/1h7cI751ZtOt2Pt93R9DYT0gjIFrqLZRMhXfdNw9rbys/edit

**Comment by julianpistorius** [comment]
Is this enough to close for now?
