### ISSUE TITLE
Problem: Website is out of date

### ISSUE THREAD

**Issue by julianpistorius** [resbazaz/festival2023#6]
Visitors to the website should know what we're about, and why they might want to participate.

Also see #5 .

**Comment by jcoliver** [comment]
See also https://github.com/resbazaz/studyGroup/issues/34

**Comment by Aariq** [comment]
PR to update website: https://github.com/resbazaz/studyGroup/pull/35/files

**Comment by val-pf** [comment]
website seems okay now, except a few smaller issues. New tab for ResBaz 2023 was created and bios updated. this is a continuing issue, but I will mark it as closed since the website is now in much better shape.
